### ISSUE TITLE
Search Example

### ISSUE THREAD

**Issue by JsbB07** [acumenbrands/rest_suite#37]
Hello,

I have gotten the Saved Search to work but after several days I haven't been able to successfully upload params for a Custom Search. The puzzling part is the arrays of Search filters and columns. Can someone post a json example to return a Search?

I have tried several versions, here is what I have been sending:

{
 "record_type": "item",
 "lower_bound": "0",
 "batch_size": "100",
 "searchFilters": [
                    {
                         "name":"department" ,
                         "operator":"is",
                         "value":"my : department"
                         }
                    ],
 "searchColumns": [
                         "Name",
                         "Description"
                    ]
 }

Here is a small sample of what is returned:

"Result: {"params":{"record_type":"item","batch_size":"100","lower_bound":"0"},"result":[{"id":"7","recordtype":"inventoryitem","columns":{"internalid":{"name":"7","internalid":"7"}}},{"id":"8","recordtype":"inventoryitem","columns":{"internalid":{"name":"8","internalid":"8"}}},{"id":"10","recordtype":"inventoryitem","columns":{"internalid":{"name":"10","internalid":"10"}}},

It seems to pick up the first 3 params but then ignores the rest. 

Thanks

**Comment by pigmonkey** [comment]
You need to provide the internal ID of the department, not its name. When it tries to convert `my : department` to an integer, it gets something null-ish, so in effect you are searching for all items where `department == null`.

Here's how I would use curl to search for all inventory items with a department ID of `13`:

```
$ curl \
      -H "Authorization: NLAuth nlauth_account=$NETSUITE_ACCOUNTID,nlauth_email=$NETSUITE_EMAIL,nlauth_signature=$NETSUITE_PASS,nlauth_role=$NETSUITE_ROLEID" \
      -H "Content-Type: application/json" \
      -d '{"record_type": "inventoryitem", "search_filters": [{"name": "department", "operator": "is", "value": "13"}], "search_columns": [], "lower_bound": 0}' \
      https://rest.netsuite.com/app/site/hosting/restlet.nl\?script\=$NETSUITE_SCRIPTID\&deploy\=1 | python -m json.tool
```

**Comment by JsbB07** [comment]
Pigmonkey,

Thanks, 

I used "my : department" as a placeholder on the example. I was able to get the search returning results about 15 min after posting for help. My results are returning the wrong data (I'm guessing the department by name is what is causing that). I have just global searched Netsuite but cant find a list of the department ID's. How did you come up with "13" for a department?

Thanks again!

**Comment by pigmonkey** [comment]
In the Netsuite UI you can go to your user preferences and enable the "Show Internal IDs" option. That will add an internal ID column to all lists, so you can just go to your normal list of departments and see the ID for each.

If you don't want to enable the preference, you could also customize the department view to add the internal ID to the results.

More generally speaking, I also frequently end up using the developer tools in the browser to see what values NetSuite is storing for certain fields.

If you navigate to the edit page in the NetSuite UI for an item record that is representative of the items you want to be in your search, you can then open the console in your browser's developer tools and use `nlapiGetFieldValue()` to see what value is stored for the `department` field. That would end up looking something like this:

```
>>> nlapiGetFieldValue('department')
"1"
```
NetSuite returns the string `1`, which is the internal ID of the department, instead of a string of the name of the department.

Sometimes the value that NetSuite is storing is not intuitive - -for instance, it stores checkbox values as the strings `T` or `F` instead of booleans `true` or `false` -- so I find that verifying things in the browser this way saves a lot of headache later on.

**Comment by JsbB07** [comment]
That worked great! 
Thanks
